### ISSUE TITLE
Set role for users in groups

### ISSUE THREAD

**Issue by sigurdga** [strekmann/nidarholmjs#182]
For now, only for the organization's member group.

- [x] Add model Role (name, email, organization)
- [x] Add functionality for adding new roles, listing, and removing roles. (organization settings)
- [x] Show list of possible email aliases / roles (curated?) (organization.roles)
- [x] Change Group model to allow for multiple roles in "member" subdocuments
- [x] Let admin type or select role name and email on member pages - should we support multiple roles? yes, but makes it harder: Change model to accept a list of roles.
- [x] Let admin remove roles from member page
- [ ] Sync roles with mailserver and mysql database. Update and insert is easy.
- [x] Show role in member list
- [x] List all roles and email addresses in use
- [ ] ~~List all roles and email addresses that are defined but without recipients~~ (#193)
- [ ] ~~Add a way of warning admins about unused email alias / role~~ (#193)
- [ ] ~~Define roles in contacts page and list users in roles~~ (#192)

**Comment by sigurdga** [comment]
d0ddf41092f95979ad39e80062af7be0c8f18a55 fixes most of these

Needs a way to delete. Maybe it's good if we keep the roles in the central database, and when they are without recipients, they may be removed from the email alias database?
